---
# tasks file for customer

- name: All selinux reboot
  hosts: all
  become: true
  roles:
    - selinux

- name: Install nginx package on webservers
  hosts: webservers
  become: true
  roles:
    - customer

- name: Install nginx package on rrobin
  hosts: rrobin
  become: true
  roles:
    - balancer
