---
# tasks file for roles/folder
- name: Create directory "{{ pg_data }}"
  ansible.builtin.file:
    path: "{{ pg_data }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - create_directory
  
- name: Create directory "{{ pg_val }}"
  ansible.builtin.file:
    path: "{{ pg_val }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - create_directory

- name: Mount up device by label "{{ pg_data }}"
  ansible.posix.mount:
    path: "{{ pg_data }}"
    src: /dev/pg/pg_data
    fstype: ext4
    state: mounted
  tags:
    - mount

- name: Mount up device by label "{{ pg_val }}"
  ansible.posix.mount:
    path: "{{ pg_val }}"
    src: /dev/pg/pg_val
    fstype: ext4
    state: mounted
  tags:
    - mount

- name: Chown directory pgsql
  ansible.builtin.file:
    path: /pgsql
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - chown_directory
  
- name: Chown directory "{{ pg_data }}"
  ansible.builtin.file:
    path: "{{ pg_data }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - chown_directory

- name: Chown directory "{{ pg_val }}"
  ansible.builtin.file:
    path: "{{ pg_val }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - chown_directory